name: AMBER
options:
  bundleIdPrefix: com.amber
  deploymentTarget:
    iOS: "16.0"
  defaultConfig: Debug
  xcodeVersion: "15.0"
settings:
  base:
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "16.0"
    TARGETED_DEVICE_FAMILY: "1,2"
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"

targets:
  AMBER:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: AMBER
        excludes:
          - "**/*.md"
          - "Resources/Music/**"
      - path: AMBER/Resources/Music
        type: folder
        buildPhase: resources
    info:
      path: AMBER/Info.plist
      properties:
        CFBundleDisplayName: AMBER
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0"
        LSRequiresIPhoneOS: true
        UIApplicationSupportsIndirectInputEvents: true
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UILaunchScreen: {}
        UIUserInterfaceStyle: Dark
        CFBundleURLTypes:
          - CFBundleURLSchemes:
              - amber
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.amber.app
        SWIFT_VERSION: "5.9"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_ENTITLEMENTS: AMBER/AMBER.entitlements
    dependencies:
      - target: AMBERWidget
        embed: true
        codeSign: true

  AMBERWidget:
    type: app-extension
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: AMBERWidget
      - path: AMBER/Shared
    info:
      path: AMBERWidget/Info.plist
      properties:
        CFBundleDisplayName: AMBERWidget
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0"
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
    entitlements:
      path: AMBERWidget/AMBERWidget.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.amber.app.widget
        SWIFT_VERSION: "5.9"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        CODE_SIGN_ENTITLEMENTS: AMBERWidget/AMBERWidget.entitlements
    dependencies:
      - sdk: WidgetKit.framework
      - sdk: SwiftUI.framework

schemes:
  AMBER:
    build:
      targets:
        AMBER: all
    run:
      config: Debug
    profile:
      config: Release
  AMBERWidget:
    build:
      targets:
        AMBERWidget: all
        AMBER: all
    run:
      config: Debug
      environmentVariables:
        _XCWidgetKind: AMBERMoodWidget
    profile:
      config: Release
