name: AMBER
options:
  bundleIdPrefix: com.amber
  deploymentTarget:
    iOS: "16.0"
  defaultConfig: Debug
  xcodeVersion: "15.0"
settings:
  base:
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "16.0"
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"

targets:
  AMBER:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: AMBER
        excludes:
          - "**/*.md"
    info:
      path: AMBER/Info.plist
      properties:
        CFBundleDisplayName: AMBER
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0"
        LSRequiresIPhoneOS: true
        UIApplicationSupportsIndirectInputEvents: true
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UILaunchScreen:
          UIColorName: ""
        UIUserInterfaceStyle: Dark
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.amber.app
        SWIFT_VERSION: "5.9"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
